const actionsStateProvider = {
    UPDATE_FORM_MODE:'UPDATE_FORM_MODE',
    UPDATE_DATE_TIME:'UPDATE_DATE_TIME',
    UPDATE_LOCALIZATION: 'UPDATE_LOCALIZATION',
    PAGE_TITLE_DETAILS:'PAGE_TITLE_DETAILS',
    OPEN_MODAL:'OPEN_MODAL',
    SET_PAGE_BACK_BUTTON:'SET_PAGE_BACK_BUTTON',
    SET_GRID_SETTINGS:'SET_GRID_SETTINGS',
    SET_LOCAL_LOCALIZATION:'SET_LOCAL_LOCALIZATION',
    USER_DATA:'USER_DATA',
    ACOSTA_REPORT_COLUMNS:'ACOSTA_REPORT_COLUMNS',
    UDPATE_PREFERENCES: 'UDPATE_PREFERENCES',
    TOTAL_PREFERENCES: 'TOTAL_PREFERENCES',
    SET_CURRENT_PREFERENCE_NAME: 'SET_CURRENT_PREFERENCE_NAME'
  };
  export default actionsStateProvider;